### ISSUE TITLE
Freeze when running powertop or powertop --calibrate

### ISSUE THREAD

**Issue by aacebedo** [fenrus75/powertop#109]
Hi

I updated my kernel to try the incoming 6.1-rc1 (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1501278bb7ba0728b869d3399ea94b67853256a2).
when I start `powertop`, my laptop freezes (I do not see any feedback hinting to a kernel panic or whatsoever).
Running `powertop --debug` does not trigger the freeze.

What's the best way to debug this issue ?

**Comment by aacebedo** [comment]
I retried on official 6.1-rc1 and saw the same behaviour

**Comment by rottenpants466** [comment]
Same here :|

**Comment by aacebedo** [comment]
What's your machine ? 
Mine is a ROG Zephyrus G14 GA402.
There are some modifications on the 6.1-rc1 kernel for this specific model (I was looking for those TBH) so it would be helpful to know if it's coming from the machine; from the kernel or from powertop.

**Comment by aacebedo** [comment]
Note: I also tried with the official 6.1-rc1 tag and I got the same behaviour

**Comment by rottenpants466** [comment]
My machine is a MSI Summit E16 Flip(Model: A12UCT), Alder Lake cpu. I'm running kubuntu 22.10 with the kernel updated to 6.1 rc.

Installs fine but when i try to run the powertop command the laptop just freezes

**Comment by aacebedo** [comment]
exacte

> My machine is a MSI Summit E16 Flip(Model: A12UCT), Alder Lake cpu. I'm running kubuntu 22.10 with the kernel updated to 6.1 rc.
> 
> Installs fine but when i try to run the powertop command the laptop just freezes
> 
> Edit: powertop --debug command runs fine

Exact same behavior on NixOS with a custom modification to use the 6.1-rc1 (not integrated in repos yet)

`--debug` also works.

**Comment by B83C** [comment]
Same issue here on T14s Gen 3 AMD, Ryzen 6850u, was running fine a few kernel tags before. The same happens when I run radeontop, no idea why...

and also, --debug works just fine as well

**Comment by thor2002ro** [comment]
false alarm rc2 works fine

**Comment by aacebedo** [comment]
Tried it yesterday and it still crashes.

**Comment by thor2002ro** [comment]
works here... i built my 6.1-rc2 from git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git master branch 
it usually has a little extra patches than the rc..... check it out

**Comment by aacebedo** [comment]
I used the tag. Can you give me the commit you used on master ?

**Comment by aacebedo** [comment]
tried https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1a2dcbdde82e3a5f1db9b2f4c48aa1aeba534fb2 still crashing.

**Comment by thor2002ro** [comment]
i built it with gcc and freezing is back.... lol so its something compiler related....

**Comment by knurd** [comment]
Anyone tried to bisect this and report this upstream (e.g. to the Linux developers). I'm doing this now, but I wonder if maybe someone else did that already.

**Comment by diegomontoya** [comment]
Fedora 38 rawhide with 6.1.0-0.rc1.20221019gitaae703b02f92.17.fc38 on amd zen3 6850h HP laptop has exact same issue. Instant lockup with blank screen when manually calling powertop.

**Comment by aacebedo** [comment]
> Anyone tried to bisect this and report this upstream (e.g. to the Linux developers). I'm doing this now, but I wonder if maybe someone else did that already.

I did not. 
I started to see it 1 or 2  commits before rc1. It was here for sure at rc1 tag.

**Comment by knurd** [comment]
# first bad commit: [838d9bb62d132ec3baf1b5aba2e95ef9a7a9a3cd] perf: Use sample_flags for raw_data

Reverting that commit in master fixes the issue for me. Applying https://lore.kernel.org/lkml/20221020070657.21571-2-atrajeev@linux.vnet.ibm.com/ does not.

**Comment by knurd** [comment]
This fixed it for me:
https://lore.kernel.org/all/20221012143857.48198-1-james.clark@arm.com/

**Comment by aacebedo** [comment]
Do you know if the commit you mentioned is going to be integrated in the master? It says not reachable from any branch for the moment.

**Comment by knurd** [comment]
> Do you know if the commit you mentioned is going to be integrated in the master?

You mean this fix? https://lore.kernel.org/all/20221012143857.48198-1-james.clark@arm.com/ Yes, it'll likely be merged this week.

**Comment by aacebedo** [comment]
great !
It strongly impact the use of my machine as I see big battery life differences when I am not running the auto-tune feature of powertop. I tried power-profile-daemon and tlp but it is not as efficient.

**Comment by thor2002ro** [comment]
the interesting part is why does it work when compiled with clang..... :))))

**Comment by aacebedo** [comment]
Tried HEAD of next (https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/snapshot/linux-next-fd8dab197cca2746e1fcd399a218eec5164726d4.tar.gz) and it solves the problem.
I checked that the lines modified by the patch mentioned by @knurd are in this branch. 
Now just have to wait for this to be upstreamed.

I guess I shall close this issue as it is not related to powertop.

**Comment by knurd** [comment]
> Now just have to wait for this to be upstreamed.

I expect that to happen tomorrow, e.g. before 6.1-rc3 is released

**Comment by aacebedo** [comment]
Cool. I'll wait for the tag then and update the related files in nixpkgs to point on it.

**Comment by paulmenzel** [comment]
@aacebedo, any updates? Is the issue fixed, so it can be closed?

**Comment by aacebedo** [comment]
Yes it is fixed

**Comment by spusuf** [comment]
Hi same issue on latest debian 12.

**Comment by paulmenzel** [comment]
> Hi same issue on latest debian 12.

Please open a new issue with your system details.
