### ISSUE TITLE
Typo: Rosted -> Rostedt

### ISSUE THREAD

**Issue by compudj** [fenrus75/powertop#42]
https://github.com/fenrus75/powertop/blob/4da1908824f62436ed0636a614d174c08dc3b6ac/README#L143

I am pretty sure Steven's last name is spelled "Rostedt".

**Comment by gkammela** [comment]
@compudj , thanks for pointing that out. We will fix it

**Comment by thac0** [comment]
@compudj Thanks for that. I'm baking an extensive README rewrite. I'll add a fix for that in the forthcoming series.
